### PR TITLE
Rename and regenerate fixtures. Import fix.

### PR DESCRIPTION
**Pull request by juanjux**
Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

### CODE REVIEW

**Comment by mcuadros** [comment]
but... the language its empty, should be PHP no?

**Comment by juanjux** [comment]
Currently the language is filled by the server since it's the one potentially calling enry, but the tests connect to the driver directly. Maybe we could fill it in the SDK if the user specified a language but the response (from the driver container) is empty.

**Comment by mcuadros** [comment]
the language in this calls should be filed by the generic part of driver in the SDK, the behavior of the standalone gRPC server should be the same of the bblfshd

**Comment by juanjux** [comment]
I'll move the call to enry to the SDK then if you don't have any problem with that.

**Comment by juanjux** [comment]
No enry, I'll just make the SDK fill the Response.Language if the Request.Language was filled, which should fix this. I'll update this PR once that's done.

https://github.com/bblfsh/sdk/issues/210

**Comment by juanjux** [comment]
@mcuadros integration tests updated with the SDK from PR bblfsh/sdk/pull/211 (PTAL when you can), now they have the language (CI will probably fail until the SDK's PR is merged).

**Comment by juanjux** [comment]
SDK tagged, this can be merged now.

**Pull request merged**
